name = "TriSpinD"
uuid = "0c281575-ae0b-4e2e-8635-954d8b3b9517"
version = "1.0.0-DEV"
authors = ["Hao Zhang"]

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
ITensorMPS = "0d1a4710-d33b-49a5-8f18-73bdf49b47e2"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[extensions]
TriSpinDPlotExt = "GLMakie"

[compat]
FFTW = "1.10.0"
ITensorMPS = "0.3.23"
ITensors = "0.9.14"
LinearAlgebra = "1.12.0"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
