name = "TriSpinD"
uuid = "0c281575-ae0b-4e2e-8635-954d8b3b9517"
authors = ["Hao Zhang"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
